// alumniData.ts
// Static alumni data for user cards, profile, etc. (replaces LinkedIn integration)

export const alumniData = [
  {
    name: "Aarav Sharma",
    email: "aarav.sharma01@gmail.com",
    linkedin: "https://www.linkedin.com/in/aarav-sharma",
    college: "Indian Institute of Technology Delhi",
  },
  {
    name: "Priya Nair",
    email: "priya.nair92@yahoo.com",
    linkedin: "https://www.linkedin.com/in/priya-nair",
    college: "University of Mumbai",
  },
  {
    name: "Rohan Verma",
    email: "rohan.verma88@outlook.com",
    linkedin: "https://www.linkedin.com/in/rohan-verma",
    college: "Birla Institute of Technology and Science, Pilani",
  },
  {
    name: "Ananya Gupta",
    email: "ananya.gupta22@gmail.com",
    linkedin: "https://www.linkedin.com/in/ananya-gupta",
    college: "Delhi University",
  },
  {
    name: "Karan Mehta",
    email: "karan.mehta11@hotmail.com",
    linkedin: "https://www.linkedin.com/in/karan-mehta",
    college: "IIM Ahmedabad",
  },
  {
    name: "Sneha Reddy",
    email: "sneha.reddy09@gmail.com",
    linkedin: "https://www.linkedin.com/in/sneha-reddy",
    college: "Osmania University",
  },
  {
    name: "Vikram Iyer",
    email: "vikram.iyer77@gmail.com",
    linkedin: "https://www.linkedin.com/in/vikram-iyer",
    college: "IIT Bombay",
  },
  {
    name: "Meera Das",
    email: "meera.das33@gmail.com",
    linkedin: "https://www.linkedin.com/in/meera-das",
    college: "Jadavpur University",
  },
  {
    name: "Siddharth Kulkarni",
    email: "sid.kulkarni91@gmail.com",
    linkedin: "https://www.linkedin.com/in/siddharth-kulkarni",
    college: "Savitribai Phule Pune University",
  },
  {
    name: "Pooja Mishra",
    email: "pooja.mishra55@gmail.com",
    linkedin: "https://www.linkedin.com/in/pooja-mishra",
    college: "Banaras Hindu University",
  },
  {
    name: "Arjun Patel",
    email: "arjun.patel87@gmail.com",
    linkedin: "https://www.linkedin.com/in/arjun-patel",
    college: "IIT Kanpur",
  },
  {
    name: "Divya Singh",
    email: "divya.singh24@gmail.com",
    linkedin: "https://www.linkedin.com/in/divya-singh",
    college: "Aligarh Muslim University",
  },
  {
    name: "Rahul Choudhary",
    email: "rahul.choudhary64@gmail.com",
    linkedin: "https://www.linkedin.com/in/rahul-choudhary",
    college: "NIT Trichy",
  },
  {
    name: "Shreya Ghosh",
    email: "shreya.ghosh02@gmail.com",
    linkedin: "https://www.linkedin.com/in/shreya-ghosh",
    college: "Presidency University, Kolkata",
  },
  {
    name: "Manish Kumar",
    email: "manish.kumar74@gmail.com",
    linkedin: "https://www.linkedin.com/in/manish-kumar",
    college: "IIT Kharagpur",
  },
  {
    name: "Aditi Joshi",
    email: "aditi.joshi88@gmail.com",
    linkedin: "https://www.linkedin.com/in/aditi-joshi",
    college: "Symbiosis International University",
  },
  {
    name: "Nikhil Agarwal",
    email: "nikhil.agarwal23@gmail.com",
    linkedin: "https://www.linkedin.com/in/nikhil-agarwal",
    college: "IIM Bangalore",
  },
  {
    name: "Ritika Kapoor",
    email: "ritika.kapoor55@gmail.com",
    linkedin: "https://www.linkedin.com/in/ritika-kapoor",
    college: "Panjab University",
  },
  {
    name: "Ashwin Menon",
    email: "ashwin.menon72@gmail.com",
    linkedin: "https://www.linkedin.com/in/ashwin-menon",
    college: "Cochin University of Science and Technology",
  },
  {
    name: "Neha Bansal",
    email: "neha.bansal93@gmail.com",
    linkedin: "https://www.linkedin.com/in/neha-bansal",
    college: "Jamia Millia Islamia",
  },
  {
    name: "Gaurav Sinha",
    email: "gaurav.sinha67@gmail.com",
    linkedin: "https://www.linkedin.com/in/gaurav-sinha",
    college: "IIT Roorkee",
  },
  {
    name: "Simran Kaur",
    email: "simran.kaur32@gmail.com",
    linkedin: "https://www.linkedin.com/in/simran-kaur",
    college: "Guru Nanak Dev University",
  },
  {
    name: "Aditya Malhotra",
    email: "aditya.malhotra21@gmail.com",
    linkedin: "https://www.linkedin.com/in/aditya-malhotra",
    college: "IIM Calcutta",
  },
  {
    name: "Kavya Rao",
    email: "kavya.rao56@gmail.com",
    linkedin: "https://www.linkedin.com/in/kavya-rao",
    college: "Christ University, Bangalore",
  },
  {
    name: "Harsh Jain",
    email: "harsh.jain77@gmail.com",
    linkedin: "https://www.linkedin.com/in/harsh-jain",
    college: "NMIMS Mumbai",
  },
  {
    name: "Ishita Sen",
    email: "ishita.sen49@gmail.com",
    linkedin: "https://www.linkedin.com/in/ishita-sen",
    college: "St. Xavier's College, Kolkata",
  },
  {
    name: "Varun Rathi",
    email: "varun.rathi91@gmail.com",
    linkedin: "https://www.linkedin.com/in/varun-rathi",
    college: "IIT Madras",
  },
  {
    name: "Tanya Bhatt",
    email: "tanya.bhatt27@gmail.com",
    linkedin: "https://www.linkedin.com/in/tanya-bhatt",
    college: "Amity University",
  },
  {
    name: "Rajeev Pillai",
    email: "rajeev.pillai73@gmail.com",
    linkedin: "https://www.linkedin.com/in/rajeev-pillai",
    college: "University of Kerala",
  },
  {
    name: "Swati Chatterjee",
    email: "swati.chatterjee82@gmail.com",
    linkedin: "https://www.linkedin.com/in/swati-chatterjee",
    college: "Visva-Bharati University",
  },
];
