// alumniData.ts
// Static alumni data for user cards, profile, etc. (replaces LinkedIn integration)

export const alumniData = [
  {
    name: "Harsh Patidar",
    email: "harshpatidar18@gmail.com",
    linkedin: "https://www.linkedin.com/in/harshpatidar18",
    college: "Devi Ahilya Vishwavidhyalaya",
    role: "Software Engineer",
    skills: ["React", "TypeScript", "Node.js", "C++"],
    company: "Google",
  },
  {
    name: "Priya Nair",
    email: "priya.nair92@yahoo.com",
    linkedin: "https://www.linkedin.com/in/priya-nair",
    college: "University of Mumbai",
    role: "Product Manager",
    skills: ["Product Management", "Agile", "Scrum", "Roadmapping"],
    company: "Amazon",
  },
  {
    name: "Rohan Verma",
    email: "rohan.verma88@outlook.com",
    linkedin: "https://www.linkedin.com/in/rohan-verma",
    college: "Birla Institute of Technology and Science, Pilani",
    role: "Data Scientist",
    skills: ["Python", "Machine Learning", "Data Analysis", "SQL"],
    company: "Microsoft",
  },
  {
    name: "Ananya Gupta",
    email: "ananya.gupta22@gmail.com",
    linkedin: "https://www.linkedin.com/in/ananya-gupta",
    college: "Delhi University",
    role: "UX Designer",
    skills: ["Figma", "Adobe XD", "User Research", "Prototyping"],
    company: "Facebook",
  },
  {
    name: "Karan Mehta",
    email: "karan.mehta11@hotmail.com",
    linkedin: "https://www.linkedin.com/in/karan-mehta",
    college: "IIM Ahmedabad",
    role: "DevOps Engineer",
    skills: ["AWS", "Docker", "Kubernetes", "CI/CD"],
    company: "Netflix",
  },
  {
    name: "Sneha Reddy",
    email: "sneha.reddy09@gmail.com",
    linkedin: "https://www.linkedin.com/in/sneha-reddy",
    college: "Osmania University",
    role: "Full Stack Developer",
    skills: ["JavaScript", "Node.js", "Express", "MongoDB"],
    company: "LinkedIn",
  },
  {
    name: "Vikram Iyer",
    email: "vikram.iyer77@gmail.com",
    linkedin: "https://www.linkedin.com/in/vikram-iyer",
    college: "IIT Bombay",
    role: "Frontend Developer",
    skills: ["HTML", "CSS", "JavaScript", "React"],
    company: "Adobe",
  },
  {
    name: "Meera Das",
    email: "meera.das33@gmail.com",
    linkedin: "https://www.linkedin.com/in/meera-das",
    college: "Jadavpur University",
    role: "Backend Engineer",
    skills: ["Java", "Spring Boot", "MySQL", "REST APIs"],
    company: "SAP",
  },
  {
    name: "Siddharth Kulkarni",
    email: "sid.kulkarni91@gmail.com",
    linkedin: "https://www.linkedin.com/in/siddharth-kulkarni",
    college: "Savitribai Phule Pune University",
    role: "Mobile Developer",
    skills: ["Kotlin", "Swift", "React Native", "Flutter"],
    company: "Uber",
  },
  {
    name: "Pooja Mishra",
    email: "pooja.mishra55@gmail.com",
    linkedin: "https://www.linkedin.com/in/pooja-mishra",
    college: "Banaras Hindu University",
    role: "AI Engineer",
    skills: ["Python", "TensorFlow", "PyTorch", "NLP"],
    company: "IBM",
  },
  {
    name: "Arjun Patel",
    email: "arjun.patel87@gmail.com",
    linkedin: "https://www.linkedin.com/in/arjun-patel",
    college: "IIT Kanpur",
    role: "Software Engineer",
    skills: ["C++", "Java", "Algorithms", "System Design"],
    company: "Apple",
  },
  {
    name: "Divya Singh",
    email: "divya.singh24@gmail.com",
    linkedin: "https://www.linkedin.com/in/divya-singh",
    college: "Aligarh Muslim University",
    role: "Product Manager",
    skills: ["Product Strategy", "User Stories", "Wireframing", "Leadership"],
    company: "Salesforce",
  },
  {
    name: "Rahul Choudhary",
    email: "rahul.choudhary64@gmail.com",
    linkedin: "https://www.linkedin.com/in/rahul-choudhary",
    college: "NIT Trichy",
    role: "Data Scientist",
    skills: ["R", "Python", "Data Visualization", "Big Data"],
    company: "Twitter",
  },
  {
    name: "Shreya Ghosh",
    email: "shreya.ghosh02@gmail.com",
    linkedin: "https://www.linkedin.com/in/shreya-ghosh",
    college: "Presidency University, Kolkata",
    role: "UX Designer",
    skills: ["Sketch", "InVision", "User Testing", "Interaction Design"],
    company: "Pinterest",
  },
  {
    name: "Manish Kumar",
    email: "manish.kumar74@gmail.com",
    linkedin: "https://www.linkedin.com/in/manish-kumar",
    college: "IIT Kharagpur",
    role: "DevOps Engineer",
    skills: ["Jenkins", "Ansible", "Terraform", "Linux"],
    company: "Red Hat",
  },
  {
    name: "Aditi Joshi",
    email: "aditi.joshi88@gmail.com",
    linkedin: "https://www.linkedin.com/in/aditi-joshi",
    college: "Symbiosis International University",
    role: "Full Stack Developer",
    skills: ["Vue.js", "Django", "PostgreSQL", "GraphQL"],
    company: "Shopify",
  },
  {
    name: "Nikhil Agarwal",
    email: "nikhil.agarwal23@gmail.com",
    linkedin: "https://www.linkedin.com/in/nikhil-agarwal",
    college: "IIM Bangalore",
    role: "Frontend Developer",
    skills: ["Angular", "TypeScript", "RxJS", "NgRx"],
    company: "Spotify",
  },
  {
    name: "Ritika Kapoor",
    email: "ritika.kapoor55@gmail.com",
    linkedin: "https://www.linkedin.com/in/ritika-kapoor",
    college: "Panjab University",
    role: "Backend Engineer",
    skills: ["Node.js", "Express", "MongoDB", "Microservices"],
    company: "Dropbox",
  },
  {
    name: "Ashwin Menon",
    email: "ashwin.menon72@gmail.com",
    linkedin: "https://www.linkedin.com/in/ashwin-menon",
    college: "Cochin University of Science and Technology",
    role: "Mobile Developer",
    skills: ["React Native", "iOS", "Android", "Firebase"],
    company: "Snapchat",
  },
  {
    name: "Neha Bansal",
    email: "neha.bansal93@gmail.com",
    linkedin: "https://www.linkedin.com/in/neha-bansal",
    college: "Jamia Millia Islamia",
    role: "AI Engineer",
    skills: ["Deep Learning", "Computer Vision", "Python", "Keras"],
    company: "NVIDIA",
  },
  {
    name: "Gaurav Sinha",
    email: "gaurav.sinha67@gmail.com",
    linkedin: "https://www.linkedin.com/in/gaurav-sinha",
    college: "IIT Roorkee",
    role: "Software Engineer",
    skills: ["Go", "Docker", "Kubernetes", "Cloud Computing"],
    company: "Dropbox",
  },
  {
    name: "Simran Kaur",
    email: "simran.kaur32@gmail.com",
    linkedin: "https://www.linkedin.com/in/simran-kaur",
    college: "Guru Nanak Dev University",
    role: "Product Manager",
    skills: ["Market Research", "Roadmap Planning", "Stakeholder Management", "Agile"],
    company: "eBay",
  },
  {
    name: "Aditya Malhotra",
    email: "aditya.malhotra21@gmail.com",
    linkedin: "https://www.linkedin.com/in/aditya-malhotra",
    college: "IIM Calcutta",
    role: "Data Scientist",
    skills: ["SQL", "Python", "Machine Learning", "Data Visualization"],
    company: "Airbnb",
  },
  {
    name: "Kavya Rao",
    email: "kavya.rao56@gmail.com",
    linkedin: "https://www.linkedin.com/in/kavya-rao",
    college: "Christ University, Bangalore",
    role: "UX Designer",
    skills: ["Adobe XD", "Figma", "User Research", "Wireframing"],
    company: "Canva",
  },
  {
    name: "Harsh Jain",
    email: "harsh.jain77@gmail.com",
    linkedin: "https://www.linkedin.com/in/harsh-jain",
    college: "NMIMS Mumbai",
    role: "DevOps Engineer",
    skills: ["AWS", "Docker", "CI/CD", "Linux"],
    company: "Atlassian",
  },
  {
    name: "Ishita Sen",
    email: "ishita.sen49@gmail.com",
    linkedin: "https://www.linkedin.com/in/ishita-sen",
    college: "St. Xavier's College, Kolkata",
    role: "Full Stack Developer",
    skills: ["MERN Stack", "GraphQL", "TypeScript", "Docker"],
    company: "GitHub",
  },
  {
    name: "Varun Rathi",
    email: "varun.rathi91@gmail.com",
    linkedin: "https://www.linkedin.com/in/varun-rathi",
    college: "IIT Madras",
    role: "Frontend Developer",
    skills: ["React", "Redux", "JavaScript", "CSS"],
    company: "Twitter",
  },
  {
    name: "Tanya Bhatt",
    email: "tanya.bhatt27@gmail.com",
    linkedin: "https://www.linkedin.com/in/tanya-bhatt",
    college: "Amity University",
    role: "Backend Engineer",
    skills: ["Python", "Django", "PostgreSQL", "REST APIs"],
    company: "Zomato",
  },
  {
    name: "Rajeev Pillai",
    email: "rajeev.pillai73@gmail.com",
    linkedin: "https://www.linkedin.com/in/rajeev-pillai",
    college: "University of Kerala",
    role: "Mobile Developer",
    skills: ["Flutter", "Dart", "iOS", "Android"],
    company: "Ola",
  },
  {
    name: "Swati Chatterjee",
    email: "swati.chatterjee82@gmail.com",
    linkedin: "https://www.linkedin.com/in/swati-chatterjee",
    college: "Visva-Bharati University",
    role: "AI Engineer",
    skills: ["Python", "Machine Learning", "NLP", "TensorFlow"],
    company: "CognitiveScale",
  },
];
